require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TestAds' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'FBAudienceNetwork', '~> 5.10.1'
  pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '7.1.1'
  pod 'FBSDKShareKit', '7.1.1'
  pod 'FBSDKLoginKit', '7.1.1'

target 'TestAdsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TestAds-tvOS' do
  # Pods for TestAds-tvOS

  target 'TestAds-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
